services:
  pwgen:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwgen.rule=Host(`pw.9level.network`)"
      - "traefik.http.routers.pwgen.entrypoints=web"
      - "traefik.http.services.pwgen.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
