version: '3.8'

services:
  pwgen:
    image: registry.9level.dev/pwgen:latest
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pwgen.rule=Host(`pw.9level.com.br`) || Host(`pw.9level.dev`)"
        - "traefik.http.routers.pwgen.entrypoints=websecure"
        - "traefik.http.routers.pwgen.tls.certresolver=letsencrypt"
        - "traefik.http.routers.pwgen.middlewares=waf-chain-indexable@file"
        - "traefik.http.services.pwgen.loadbalancer.server.port=80"
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback

networks:
  proxy:
    external: true
